name : Deploy React App to Github Pages

on:
 push:
  branches: 
   - main

permissions:
  contents: write

jobs:
  build-and-deploys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - run: npm ci
      - run: npm run build

      # Checkout or tạo branch gh-pages cục bộ
      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
          git switch gh-pages
          git rm -rf .  # Xoá sạch nội dung cũ

      # Copy nội dung build sang thư mục root branch gh-pages
      - name: Copy build files
        run: |
          cp -r ./dist/* ./

      # Commit & push thay đổi
      # Commit.
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Manual deploy via GitHub Actions [skip ci]" || echo "No changes to commit"
          git push origin gh-pages --force 
        